octomap_server:
  ros__parameters:
    resolution: 0.05
    frame_id: "world"
    sensor_model:
      max_range: 3.0
      hit: 0.7
      miss: 0.4
      min: 0.12
      max: 0.97
    latch: false
    filter_ground: false
    filter_speckles: true
    pointcloud_min_z: -1.0
    pointcloud_max_z: 2.0
